name: Build after an update

on:
  push:
    paths:
      - flake.lock
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = flakes nix-command
            flake-registry = https://github.com/c4f3z1n/nix-registry/releases/latest/download/registry.json
            nix-path = nixpkgs=flake:nixpkgs
      - uses: actions/checkout@v4
      - id: build
        run: cat "$(nix build --no-link --print-out-paths)"
