name: Test action
on:
  schedule:
    - cron: "0 0 * * 0,3" # every Sunday and Wednesday at 00:00;
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |
            experimental-features = flakes nix-command
            nix-path = nixpkgs=github:nixos/nixpkgs/nixos-23.11-small
      - run: |
          nix flake update --refresh
          nix build
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add flake.lock result
          git restore .
          git commit -m "Test action"
      - uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          signoff: false
          branch: flake-update
          delete-branch: true
          title: Test action
          assignees: ${{ github.actor }}
          draft: false
