name: Update flake.lock

on:
  schedule:
    - cron: "0 0 * * 0,3" # every Sunday and Wednesday at 00:00;
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = flakes nix-command
            flake-registry = https://github.com/c4f3z1n/nix-registry/releases/latest/download/registry.json
            nix-path = nixpkgs=flake:nixpkgs
      - name: Setup git
        run: |
          git config --local push.autoSetupRemote true
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Update
        run: |
          git switch -c "update/$(date '+%Y-%m-%d')"
          nix flake update --commit-lock-file
          nix fmt flake.lock
          git add flake.lock
          git commit --amend --no-edit
      - name: Push
        run: |
          git push
          gh pr create --fill
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
