name: Update flake.lock

on:
  schedule:
    - cron: "0 0 * * 0,3" # every Sunday and Wednesday at 00:00;
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |
            experimental-features = flakes nix-command
            nix-path = nixpkgs=github:nixos/nixpkgs/nixos-23.11-small
      - name: Setup git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - id: update
        name: Update flake.lock
        run: |
          nix flake update --commit-lock-file
          nix fmt flake.lock
          git add flake.lock
          git commit --amend --no-edit
      - id: date
        run: printf "TODAY=%s\n" "$(date '+%Y-%m-%d')" | tee -a $GITHUB_OUTPUT
      - uses: peter-evans/create-pull-request@v6
        with:
          title: ${{ steps.date.outputs.TODAY }}
          body: ${{ steps.update.outputs.PR_BODY }}
          branch: ${{ steps.date.outputs.TODAY }}
          delete-branch: true
          draft: false
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
