name: Update registry
on:
  schedule:
    - cron: "0 0 * * 0" # runs weekly on Sunday at 00:00
  workflow_dispatch: # allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |
            experimental-features = flakes nix-command
            flake-registry = ${{ github.workspace }}/registry.json
            nix-path = nixpkgs=flake:nixpkgs
      - run: |
          nix build --no-write-lock-file
          cp -fv result registry.json
          nix fmt --no-write-lock-file
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add registry.json
          git restore .
          git commit -m "Updated registry"
      - uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          # author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          signoff: false
          branch: flake-update
          delete-branch: true
          title: Updated registry
          assignees: ${{ github.actor }}
          draft: false
